version: '3'
services:
  react-ui:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: frontend

  api:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    container_name: backend
    volumes:
      - ./data:/usr/src/app/data
